# Site settings
title: approaching236 (blog)
email: vgrato@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Person first programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://approaching236.github.io" # the base hostname & protocol for your site
github_username:  approaching236

# Build settings
markdown: kramdown
google_analytics: "G-6R6NL7589H"
